
import Project.ConnectionProvider;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kiam
 */

public class amb extends javax.swing.JFrame {

    /**
     * Creates new form amb
     */
    public int j1, j2, j3, j4, j5, j6, j7, j8, j9, j10, j11, j12;
    
    public amb() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(246,249,246));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(246, 249, 246));
        setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        setLocation(new java.awt.Point(131, 280));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1250, 459));

        jPanel1.setBackground(new java.awt.Color(246, 249, 246));

        jPanel2.setBackground(new java.awt.Color(246, 249, 246));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(246, 249, 246));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(".");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(246, 249, 246));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(".");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(246, 249, 246));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(".");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(246, 249, 246));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(".");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(246, 249, 246));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(246, 249, 246));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText(".");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(246, 249, 246));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText(".");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(246, 249, 246));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText(".");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(246, 249, 246));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText(".");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(246, 249, 246));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(246, 249, 246));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText(".");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(246, 249, 246));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText(".");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(246, 249, 246));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText(".");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(246, 249, 246));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText(".");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(128, 128, 128));
        jLabel13.setText("Total Ambulance");

        jLabel14.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(128, 128, 128));
        jLabel14.setText("Occupied Ambulance");

        jLabel15.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(128, 128, 128));
        jLabel15.setText("Available Ambulance");

        jButton1.setBackground(new java.awt.Color(147, 26, 37));
        jButton1.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(203, 203, 203)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(472, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel17)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        pageRefresh();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
       
        
            int j, id=1;
            
        try
        {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            if(j1==0)
            { 
                j=1;
                st.executeUpdate("UPDATE amb set car1 = '"+j+"' WHERE amb_id = '"+id+"'");
                JOptionPane.showMessageDialog(null, "Updated");
                pageRefresh();
            }
            
            else
            {
               j=0;
             st.executeUpdate("UPDATE amb set car1 = '"+j+"' WHERE amb_id = '"+id+"'"); 
            JOptionPane.showMessageDialog(null, "Updated");
            pageRefresh();
            }
              
        }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,".......Don't Success!");
            }
       
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        int j,id=1;
            
            try
            {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
           if(j2==1)
            { 
               j=0;
                st.executeUpdate("UPDATE amb set car2 = '"+j+"' WHERE amb_id = '"+id+"'");
                JOptionPane.showMessageDialog(null, "Updated");
                pageRefresh();
            }
            
            else
           {
                j=1;
                st.executeUpdate("UPDATE amb set car2 = '"+j+"' WHERE amb_id = '"+id+"'"); 
                JOptionPane.showMessageDialog(null, "Updated");
                pageRefresh();
           }
            
        }catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,".......Don't Success!");
                }
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        int j,id=1;
            
            try
            {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
           if(j3==1)
            { 
               j=0;
                st.executeUpdate("UPDATE amb set car3 = '"+j+"' WHERE amb_id = '"+id+"'");
                JOptionPane.showMessageDialog(null, "Updated");
                pageRefresh();
            }
            
            else
           {
                j=1;
                st.executeUpdate("UPDATE amb set car3 = '"+j+"' WHERE amb_id = '"+id+"'"); 
                JOptionPane.showMessageDialog(null, "Updated");
                pageRefresh();
           }
            
        }catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,".......Don't Success!");
                }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        int j,id=1;
            
            try
            {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
           if(j4==1)
            { 
               j=0;
                st.executeUpdate("UPDATE amb set car4 = '"+j+"' WHERE amb_id = '"+id+"'");
                JOptionPane.showMessageDialog(null, "Updated");
                pageRefresh();
            }
            
            else
           {
                j=1;
                st.executeUpdate("UPDATE amb set car4 = '"+j+"' WHERE amb_id = '"+id+"'"); 
                JOptionPane.showMessageDialog(null, "Updated");
                pageRefresh();
           }
            
        }catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,".......Don't Success!");
                }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        int j,id=1;
            
            try
            {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
           if(j7==1)
            { 
               j=0;
                st.executeUpdate("UPDATE amb set car7 = '"+j+"' WHERE amb_id = '"+id+"'");
                JOptionPane.showMessageDialog(null, "Updated");
                pageRefresh();
            }
            
            else
           {
                j=1;
                st.executeUpdate("UPDATE amb set car7 = '"+j+"' WHERE amb_id = '"+id+"'"); 
                JOptionPane.showMessageDialog(null, "Updated");
                pageRefresh();
           }
            
        }catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,".......Don't Success!");
                }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        int j,id=1;
            
            try
            {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
           if(j8==1)
            { 
               j=0;
                st.executeUpdate("UPDATE amb set car8 = '"+j+"' WHERE amb_id = '"+id+"'");
                JOptionPane.showMessageDialog(null, "Updated");
                pageRefresh();
            }
            
            else
           {
                j=1;
                st.executeUpdate("UPDATE amb set car8 = '"+j+"' WHERE amb_id = '"+id+"'"); 
                JOptionPane.showMessageDialog(null, "Updated");
                pageRefresh();
           }
            
        }catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,".......Don't Success!");
                }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        int j,id=1;
            
            try
            {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
           if(j9==1)
            { 
               j=0;
                st.executeUpdate("UPDATE amb set car9 = '"+j+"' WHERE amb_id = '"+id+"'");
                JOptionPane.showMessageDialog(null, "Updated");
                pageRefresh();
            }
            
            else
           {
                j=1;
                st.executeUpdate("UPDATE amb set car9 = '"+j+"' WHERE amb_id = '"+id+"'"); 
                JOptionPane.showMessageDialog(null, "Updated");
                pageRefresh();
           }
            
        }catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,".......Don't Success!");
                }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        int j,id=1;
            
            try
            {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
           if(j10==1)
            { 
               j=0;
                st.executeUpdate("UPDATE amb set car10 = '"+j+"' WHERE amb_id = '"+id+"'");
                JOptionPane.showMessageDialog(null, "Updated");
                pageRefresh();
            }
            
            else
           {
                j=1;
                st.executeUpdate("UPDATE amb set car10 = '"+j+"' WHERE amb_id = '"+id+"'"); 
                JOptionPane.showMessageDialog(null, "Updated");
                pageRefresh();
           }
            
        }catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,".......Don't Success!");
                }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        int j,id=1;
            
            try
            {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
           if(j11==1)
            { 
               j=0;
                st.executeUpdate("UPDATE amb set car11 = '"+j+"' WHERE amb_id = '"+id+"'");
                JOptionPane.showMessageDialog(null, "Updated");
                pageRefresh();
            }
            
            else
           {
                j=1;
                st.executeUpdate("UPDATE amb set car11 = '"+j+"' WHERE amb_id = '"+id+"'"); 
                JOptionPane.showMessageDialog(null, "Updated");
                pageRefresh();
           }
            
        }catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,".......Don't Success!");
                }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        int j,id=1;
            
            try
            {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
           if(j5==1)
            { 
               j=0;
                st.executeUpdate("UPDATE amb set car5 = '"+j+"' WHERE amb_id = '"+id+"'");
                JOptionPane.showMessageDialog(null, "Updated");
                pageRefresh();
            }
            
            else
           {
                j=1;
                st.executeUpdate("UPDATE amb set car5 = '"+j+"' WHERE amb_id = '"+id+"'"); 
                JOptionPane.showMessageDialog(null, "Updated");
                pageRefresh();
           }
            
        }catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,".......Don't Success!");
                }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        int j,id=1;
            
            try
            {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
           if(j12==1)
            { 
               j=0;
                st.executeUpdate("UPDATE amb set car12 = '"+j+"' WHERE amb_id = '"+id+"'");
                JOptionPane.showMessageDialog(null, "Updated");
                pageRefresh();
            }
            
            else
           {
                j=1;
                st.executeUpdate("UPDATE amb set car12 = '"+j+"' WHERE amb_id = '"+id+"'"); 
                JOptionPane.showMessageDialog(null, "Updated");
                pageRefresh();
           }
            
        }catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,".......Don't Success!");
                }
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        int j,id=1;
            
            try
            {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
           if(j6==1)
            { 
               j=0;
                st.executeUpdate("UPDATE amb set car6 = '"+j+"' WHERE amb_id = '"+id+"'");
                JOptionPane.showMessageDialog(null, "Updated");
                pageRefresh();
            }
            
            else
           {
                j=1;
                st.executeUpdate("UPDATE amb set car6 = '"+j+"' WHERE amb_id = '"+id+"'"); 
                JOptionPane.showMessageDialog(null, "Updated");
                pageRefresh();
           }
            
        }catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,".......Don't Success!");
                }
    }//GEN-LAST:event_jLabel6MouseClicked

              
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(amb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(amb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(amb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(amb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new amb().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

    private void pageRefresh() {
        
        try
        {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select *from amb");
            
            int count = 0;
            
            if(rs.next())
            {
                jLabel1.setText(rs.getString(2));
                
                jLabel1.setOpaque(true);
                if("1".equals(jLabel1.getText()))
                {
                    jLabel1.setBackground(new Color(0, 136, 145));
                    jLabel1.setText("CTG-Cha-126701");
                    count++;
                    j1 = 1;
                }
                else
                {
                    jLabel1.setBackground(new Color(232,80,91));
                    jLabel1.setText("CTG-Cha-126701");
                    j1 = 0;
                }
                
                
                jLabel2.setText(rs.getString(3));
                
                jLabel2.setOpaque(true);
                if("1".equals(jLabel2.getText()))
                {
                    jLabel2.setBackground(new Color(0, 136, 145));
                    jLabel2.setText("CTG-Cha-126702");
                    count++;
                    j2 = 1;
                }
                else
                {
                    jLabel2.setBackground(new Color(232,80,91));
                    jLabel2.setText("CTG-Cha-126702");
                    j2 = 0;
                }
                jLabel3.setText(rs.getString(4));
                jLabel3.setOpaque(true);
                if("1".equals(jLabel3.getText()))
                {
                    jLabel3.setBackground(new Color(0, 136, 145));
                    jLabel3.setText("CTG-Cha-126703");
                    count++;
                    j3=1;
                }
                else
                {
                    jLabel3.setBackground(new Color(232,80,91));
                    jLabel3.setText("CTG-Cha-126703");
                    j3=0;
                }
                jLabel4.setText(rs.getString(5));
                jLabel4.setOpaque(true);
                if("1".equals(jLabel4.getText()))
                {
                    jLabel4.setBackground(new Color(0, 136, 145));
                    jLabel4.setText("CTG-Cha-126704");
                    count++;
                    j4=1;
                }
                else
                {
                    jLabel4.setBackground(new Color(232,80,91));
                    jLabel4.setText("CTG-Cha-126704");
                    j4=0;
                }
                jLabel5.setText(rs.getString(6));
                jLabel5.setOpaque(true);
                if("1".equals(jLabel5.getText()))
                {
                    jLabel5.setBackground(new Color(0, 136, 145));
                    jLabel5.setText("CTG-Cha-126705");
                    count++;
                    j5=1;
                }
                else
                {
                    jLabel5.setBackground(new Color(232,80,91));
                    jLabel5.setText("CTG-Cha-126705");
                    j5=0;
                }
                jLabel6.setText(rs.getString(7));
                jLabel6.setOpaque(true);
                if("1".equals(jLabel6.getText()))
                {
                    jLabel6.setBackground(new Color(0, 136, 145));
                    jLabel6.setText("CTG-Cha-126707");
                    count++;
                    j6=1;
                }
                else
                {
                    jLabel6.setBackground(new Color(232,80,91));
                    jLabel6.setText("CTG-Cha-126707");
                    j6=0;
                }
                jLabel7.setText(rs.getString(8));
                jLabel7.setOpaque(true);
                if("1".equals(jLabel7.getText()))
                {
                    jLabel7.setBackground(new Color(0, 136, 145));
                    jLabel7.setText("CTG-Cha-126708");
                    count++;
                    j7=1;
                }
                else
                {
                    jLabel7.setBackground(new Color(232,80,91));
                    jLabel7.setText("CTG-Cha-126708");
                    j7=0;
                }
                jLabel8.setText(rs.getString(9));
                jLabel8.setOpaque(true);
                if("1".equals(jLabel8.getText()))
                {
                    jLabel8.setBackground(new Color(0, 136, 145));
                    jLabel8.setText("CTG-Cha-126709");
                    count++;
                    j8=1;
                }
                else
                {
                    jLabel8.setBackground(new Color(232,80,91));
                    jLabel8.setText("CTG-Cha-126709");
                    j8=0;
                }
                jLabel9.setText(rs.getString(10));
                jLabel9.setOpaque(true);
                if("1".equals(jLabel9.getText()))
                {
                    jLabel9.setBackground(new Color(0, 136, 145));
                    jLabel9.setText("CTG-Cha-126710");
                    count++;
                    j9=1;
                }
                else
                {
                    jLabel9.setBackground(new Color(232,80,91));
                    jLabel9.setText("CTG-Cha-126710");
                    j9=0;
                }
                jLabel10.setText(rs.getString(11));
                jLabel10.setOpaque(true);
                if("1".equals(jLabel10.getText()))
                {
                    jLabel10.setBackground(new Color(0, 136, 145));
                    jLabel10.setText("CTG-Cha-126711");
                    count++;
                    j10=1;
                }
                else
                {
                    jLabel10.setBackground(new Color(232,80,91));
                    jLabel10.setText("CTG-Cha-126711");
                    j10=0;
                }
                jLabel11.setText(rs.getString(12));
                jLabel11.setOpaque(true);
                if("1".equals(jLabel11.getText()))
                {
                    jLabel11.setBackground(new Color(0, 136, 145));
                    jLabel11.setText("CTG-Cha-126712");
                    count++;
                    j11=1;
                }
                else
                {
                    jLabel11.setBackground(new Color(232,80,91));
                    jLabel11.setText("CTG-Cha-126712");
                    j11=0;
                }
                jLabel12.setText(rs.getString(13));
                jLabel12.setOpaque(true);
                if("1".equals(jLabel12.getText()))
                {
                    jLabel12.setBackground(new Color(0, 136, 145));
                    jLabel12.setText("CTG-Cha-126713");
                    count++;
                    j12=1;
                }
                else
                {
                    jLabel12.setBackground(new Color(232,80,91));
                    jLabel12.setText("CTG-Cha-126713");
                    j12=0;
                }
      
                
            }
            else{
                JOptionPane.showMessageDialog(null,".......");
            }
            
            String s=String.valueOf(count);
            String s1=String.valueOf(12-count);
            jLabel16.setText("12");
            jLabel17.setText(s1);
            jLabel18.setText(s);
            
            
        }
        catch(Exception e)
                {
                  JOptionPane.showMessageDialog(null,".......Don't Success!");  
                }
        
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        
        
    }
}
